# Site settings
title: Avinash Prabhakaran
description: My Personal Website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:4000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

username: Avinash Prabhakaran
user_description: Data Scientist/Machine Learning Engineer holding a Masters degree in Data Science from the University of British Columbia.  Experience in building distributed data analysis pipelines using Spark, and solving data science problems involving time series forecasting, anomaly detection and predictive maintenance. Have interpersonal skills to engage a non-technical audience. Possess leadership qualities, organizational skills and loves challenging opportunities that offer new perspectives and collaborative experience
user_subtitle: Data Scientist/Machine Learning Engineer
email: avinashkp26@gmail.com
facebook_username: Avinash.Prabhakaran
instagram_username: ziavi7
twitter_username: ziavinash
github_username:  avinashkz

sass:
  sass_dir: css
  style: compressed
